spring:
  application:
    name: Product
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    generateUniqueName: false
    name: products
    username: chris
    password: chris
  jpa:
    hibernate:
      ddl-auto: create-drop
    showSql: true
  server:
    port: 8050