spring:
  application:
    name: Notification
  data:
    mongodb:
      username: chris
      password: chris
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      groupId: paymentGroup,orderGroup
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringSerializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: orderConfirmation:com.javalord.Notification.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.javalord.Notification.notification.kafka.payment.PaymentConfirmation

