spring:
  application:
    name: Order
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: orderConfirmation:com.javalord.Order.kafka.OrderConfirmation

